apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  selector:
    app: loadbalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 443
      targetPort: 443
