apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagerservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermanagerservice
  template:
    metadata:
      labels:
        app: usermanagerservice
    spec:
      containers:
        - name: usermanagerservice
          image: jackdelaguilavilla03/usermanagerservice:latest
          ports:
            - containerPort: 8040
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_HTTP_PORTS
              value: "8040"
            - name: ASPNETCORE_HTTPS_PORTS
              value: "8041"
