# check-changes.yml

name: Check Changes

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-service-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_services: ${{ steps.check-changes.outputs.changed_services }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for changes in services
        id: check-changes
        run: |
          changed_services=false

          if [ -n "$(git diff HEAD^ --name-only -- LoadBalancer)" ]; then
            echo "Changes detected in LoadBalancer service"
            changed_services=true
          fi

          if [ -n "$(git diff HEAD^ --name-only -- ApigatewayWithOcelot)" ]; then
            echo "Changes detected in ApiGatewayWithOcelot service"
            changed_services=true
          fi

          if [ -n "$(git diff HEAD^ --name-only -- ApigatewayWithYarp)" ]; then
            echo "Changes detected in ApiGatewayWithYarp service"
            changed_services=true
          fi

          if [ -n "$(git diff HEAD^ --name-only -- ConferenceManagerService)" ]; then
            echo "Changes detected in ConferenceManagerService service"
            changed_services=true
          fi

          if [ -n "$(git diff HEAD^ --name-only -- FeedManagerService)" ]; then
            echo "Changes detected in FeedManagerService service"
            changed_services=true
          fi

          if [ -n "$(git diff HEAD^ --name-only -- PaymentManagerService)" ]; then
            echo "Changes detected in PaymentManagerService service"
            changed_services=true
          fi

          if [ -n "$(git diff HEAD^ --name-only -- UserManagerService)" ]; then
            echo "Changes detected in UserManagerService service"
            changed_services=true
          fi

          echo "::set-output name=changed_services::$changed_services"
