on:
  push:
    branches:
      - deploy

env:
  CONTAINER_APP_ENVIRONMENT_NAME: managedEnv2024
  RESOURCE_GROUP: managedEnv20240625001418ResourceGroup
  CONTAINER_REGISTRY_NAME: registry20240625002039
  CONTAINER_REGISTRY_LOGIN_SERVER: registry20240625002039.azurecr.io

jobs:
  DeployContainerApp:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.managedEnv2024_SPN }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy with Docker Stack
        run: |
          # Configurar Docker para usar el servidor de registro de contenedores de Azure
          az acr login --name $CONTAINER_REGISTRY_NAME

          # Configurar Docker para utilizar las credenciales de Azure
          az configure --defaults acr=$CONTAINER_REGISTRY_NAME

          # Desplegar con Docker Stack en Docker Swarm
          docker stack deploy --compose-file docker-stack.yml your-stack-name  # Reemplaza 'your-stack-name' por el nombre deseado

          # Opcional: Esperar a que el despliegue esté completo (esto es un ejemplo básico)
          sleep 60  # Espera 1 minuto (ajusta según la complejidad de tu despliegue)

      - name: Verify deployment
        run: |
          # Aquí puedes agregar comandos para verificar que tu despliegue haya sido exitoso
          # Por ejemplo, puedes ejecutar comandos curl o realizar pruebas de integración

